### ISSUE TITLE
 Could not find the implementation for builder @beeman/angular-serve-nodemon:run

### ISSUE THREAD

**Issue by csimpi** [beeman/angular-serve-nodemon#1]
I am getting this error with Angular 13. Is this project deprecated/abandoned?

`Could not find the implementation for builder @beeman/angular-serve-nodemon:run`

**Comment by beeman** [comment]
Hi, yes - the last update to this project was quite a while ago 😅 

![image](https://user-images.githubusercontent.com/36491/207750056-4e61ec84-3797-460a-83be-af66f085fb17.png)
